// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torath;

#nullable disable

namespace Torath.Migrations
{
    [DbContext(typeof(TorathDbContext))]
    [Migration("20260710041407_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Torath.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MagazineIssueId")
                        .HasColumnType("int");

                    b.Property<int?>("NewspaperIssueId")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MagazineIssueId");

                    b.HasIndex("NewspaperIssueId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Torath.Entities.BaseContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BaseContent");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Torath.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tech books and articles.",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Historical documents.",
                            Name = "History"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Scientific research and journals.",
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("Torath.Entities.MagazineIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IssueNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MagazineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VolumeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MagazineId");

                    b.ToTable("MagazineIssues");
                });

            modelBuilder.Entity("Torath.Entities.NewspaperIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IssueNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewspaperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NewspaperId");

                    b.ToTable("NewspaperIssues");
                });

            modelBuilder.Entity("Torath.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Torath.Entities.Book", b =>
                {
                    b.HasBaseType("Torath.Entities.BaseContent");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 7, 10, 4, 14, 5, 691, DateTimeKind.Utc).AddTicks(646),
                            Description = "A Craftsman's Guide to Software Structure",
                            Language = "English",
                            PublicationDate = new DateTime(2017, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Prentice Hall",
                            Title = "Clean Architecture",
                            Authors = "Robert C. Martin",
                            Edition = "1st",
                            ISBN = "978-0134494166",
                            NumberOfPages = 432
                        });
                });

            modelBuilder.Entity("Torath.Entities.Magazine", b =>
                {
                    b.HasBaseType("Torath.Entities.BaseContent");

                    b.Property<string>("ISSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Magazines", (string)null);
                });

            modelBuilder.Entity("Torath.Entities.Newspaper", b =>
                {
                    b.HasBaseType("Torath.Entities.BaseContent");

                    b.ToTable("Newspapers", (string)null);
                });

            modelBuilder.Entity("Torath.Entities.ResearchPaper", b =>
                {
                    b.HasBaseType("Torath.Entities.BaseContent");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JournalOrConferenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.ToTable("ResearchPapers", (string)null);
                });

            modelBuilder.Entity("Torath.Entities.Article", b =>
                {
                    b.HasOne("Torath.Entities.MagazineIssue", "MagazineIssue")
                        .WithMany("Articles")
                        .HasForeignKey("MagazineIssueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Torath.Entities.NewspaperIssue", "NewspaperIssue")
                        .WithMany("Articles")
                        .HasForeignKey("NewspaperIssueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MagazineIssue");

                    b.Navigation("NewspaperIssue");
                });

            modelBuilder.Entity("Torath.Entities.BaseContent", b =>
                {
                    b.HasOne("Torath.Entities.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Torath.Entities.MagazineIssue", b =>
                {
                    b.HasOne("Torath.Entities.Magazine", "Magazine")
                        .WithMany("Issues")
                        .HasForeignKey("MagazineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazine");
                });

            modelBuilder.Entity("Torath.Entities.NewspaperIssue", b =>
                {
                    b.HasOne("Torath.Entities.Newspaper", "Newspaper")
                        .WithMany("Issues")
                        .HasForeignKey("NewspaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Newspaper");
                });

            modelBuilder.Entity("Torath.Entities.Book", b =>
                {
                    b.HasOne("Torath.Entities.BaseContent", null)
                        .WithOne()
                        .HasForeignKey("Torath.Entities.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torath.Entities.Magazine", b =>
                {
                    b.HasOne("Torath.Entities.BaseContent", null)
                        .WithOne()
                        .HasForeignKey("Torath.Entities.Magazine", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torath.Entities.Newspaper", b =>
                {
                    b.HasOne("Torath.Entities.BaseContent", null)
                        .WithOne()
                        .HasForeignKey("Torath.Entities.Newspaper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torath.Entities.ResearchPaper", b =>
                {
                    b.HasOne("Torath.Entities.BaseContent", null)
                        .WithOne()
                        .HasForeignKey("Torath.Entities.ResearchPaper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torath.Entities.Category", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Torath.Entities.MagazineIssue", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Torath.Entities.NewspaperIssue", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Torath.Entities.Magazine", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Torath.Entities.Newspaper", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
